import uuid
import json
import os
import time
from agents.graph import build_graph
from agents.state import AgentState
from tools.python_tool import calculate
from tools.document_tools import write_file

# Initialize tools
import tools.python_tool
import tools.document_tools
import tools.demo_tools
import tools.c_tools_integration
from tools.registry import registry

def run_sovara_task(task: str, files: list = None, knowledge_context: str = None, options: dict = None) -> dict:
    run_id = str(uuid.uuid4())
    
    initial_state: AgentState = {
        "run_id": run_id,
        "user_query": task,
        "task": "",
        "plan": None,
        "current_step": 0,
        "step_count": 0,
        "retrieved_context": [],
        "tool_results": [],
        "selected_model": "qwen3:4b",
        "execution_events": ["TASK_STARTED"],
        "final_answer": "",
        "verification_result": None,
        "risk_result": None,
        "human_review_required": False,
        "status": "RUNNING",
        "errors": [],
        "timing": {},
        "multimodal_results": [],
        "input_files": files or [],
        "file_analysis": [],
        "uncertainties": []
    }
    
    graph = build_graph()
    
    t0 = time.time()
    try:
        result_state = graph.invoke(initial_state)
        
        # Document Generation
        if result_state.get("input_files"):
            try:
                sections = [
                    {"heading": "Summary", "content": "Generated by SOVARA."},
                    {"heading": "Observations [OBSERVED]", "content": "\n".join([str(t["result"]) for t in result_state.get("tool_results", [])])},
                    {"heading": "Evidence [INFERRED]", "content": str(result_state.get("retrieved_context", []))},
                    {"heading": "Findings & Risk", "content": [result_state.get("final_answer", ""), f"Risk Level: {result_state.get('risk_result', {}).get('risk_level', 'UNKNOWN')}", f"Human Review Status: {result_state.get('human_review_required', False)}"]},
                    {"heading": "Recommended Action [RECOMMENDED]", "content": "Review required." if result_state.get("human_review_required") else "Proceed."}
                ]
                res = registry.execute("generate_docx", {
                    "filename": f"outputs/{result_state['run_id']}/Approval_Note.docx",
                    "title": "Engineering Approval Note",
                    "sections": sections
                })
                result_state["tool_results"].append({"tool": "generate_docx", "result": res})
            except Exception as e:
                result_state["errors"].append(f"Doc gen error: {e}")
                
    except Exception as e:
        initial_state["errors"].append(str(e))
        initial_state["status"] = "FAILED"
        result_state = initial_state
        
    result_state["timing"]["total_ms"] = (time.time() - t0) * 1000
        
    # Build structured outputs
    outputs_list = []
    for tr in result_state.get("tool_results", []):
        if tr.get("tool") == "generate_docx" and tr.get("result", {}).get("success"):
            r = tr["result"].get("result", {})
            outputs_list.append({
                "name": r.get("filename", "output.docx"),
                "path": r.get("path", ""),
                "type": "docx"
            })
            
    is_success = result_state["status"] == "COMPLETED"

    return {
        "success": is_success,
        "task_id": result_state["run_id"],
        "run_id": result_state["run_id"],
        "status": result_state["status"],
        "answer": result_state["final_answer"],
        "plan": result_state.get("plan", {}).get("steps", []),
        "execution": {
            "steps": result_state["execution_events"],
            "duration_ms": result_state["timing"].get("total_ms", 0)
        },
        "evidence": result_state["retrieved_context"],
        "citations": [c.get("chunk_id") for c in result_state["retrieved_context"]],
        "verification": {
            "status": result_state.get("verification_result", {}).get("verification_status", "UNKNOWN"),
            "issues": []
        } if result_state.get("verification_result") else None,
        "risk": {
            "level": result_state.get("risk_result", {}).get("risk_level", "UNKNOWN"),
            "human_review_required": result_state.get("human_review_required", False)
        } if result_state.get("risk_result") else None,
        "outputs": outputs_list,
        "models_used": [result_state.get("selected_model", "qwen3:4b")],
        "errors": result_state["errors"],
        
        # Backwards compat for old tests
        "execution_trace": result_state["execution_events"],
        "deliverables": result_state["tool_results"],
        "timing": result_state["timing"]
    }

if __name__ == "__main__":
    import sys
    import argparse
    
    parser = argparse.ArgumentParser(description="SOVARA AI Core Demo")
    parser.add_argument("query", nargs="*", default=["What is the recommended pressure for Pump P-999?"], help="The user query")
    parser.add_argument("--demo", action="store_true", help="Run the full hero demo with synthetic files")
    args = parser.parse_args()

    print("\\n==================================================")
    print(" SOVARA AI Core Demo")
    print("==================================================\\n")
    
    if args.demo:
        query = "Analyze P-101 using the provided P&ID, inspection report, maintenance spreadsheet and maintenance procedure. Identify abnormal conditions, explain the supporting evidence, perform any required calculations, assess risk, and prepare an approval recommendation."
        files = ["demo/pump_pid.png", "demo/inspection_report.pdf", "demo/pump_inspection.xlsx", "datasets/synthetic_plant/documents/P101_Maintenance_SOP.md"]
    else:
        query = " ".join(args.query)
        files = []
        
    print(f"User Query: {query}")
    if files: print(f"Input Files: {files}")
    print("\\n")
    
    result = run_sovara_task(task=query, files=files)
    
    print(f"Status: {result['status']}")
    print(f"Risk: {result['risk']['level'] if result['risk'] else 'N/A'}")
    print(f"Human Review: {result['human_review_required']}")
    print(f"Answer: {result['answer']}")
    print(f"Errors: {result['errors']}")
    print(f"Deliverables: {result['deliverables']}")
    
    print("\\nTiming metrics:")
    for k, v in result.get("timing", {}).items():
        print(f" - {k}: {v:.2f} ms")
        
    print("\\nExecution Trace:")
    for evt in result['execution_trace']:
        print(f" - {evt}")
    print(" - TASK_COMPLETED")

