import uuid
import json
import os
import time
from agents.graph import build_graph
from agents.state import AgentState
from tools.python_tool import calculate
from tools.document_tools import write_file

# Initialize tools
import tools.python_tool
import tools.document_tools
import tools.demo_tools
from tools.registry import registry

def run_sovara_task(user_query: str, files: list = None, knowledge_base: str = None) -> dict:
    run_id = str(uuid.uuid4())
    
    initial_state: AgentState = {
        "run_id": run_id,
        "user_query": user_query,
        "task": "",
        "plan": None,
        "current_step": 0,
        "step_count": 0,
        "retrieved_context": [],
        "tool_results": [],
        "selected_model": "qwen3:4b",
        "execution_events": ["TASK_STARTED"],
        "final_answer": "",
        "verification_result": None,
        "risk_result": None,
        "human_review_required": False,
        "status": "RUNNING",
        "errors": [],
        "timing": {},
        "multimodal_results": [],
        "input_files": files or [],
        "file_analysis": [],
        "uncertainties": []
    }
    
    graph = build_graph()
    
    t0 = time.time()
    try:
        result_state = graph.invoke(initial_state)
        
        # Document Generation
        if result_state.get("input_files"):
            try:
                res = registry.execute("generate_docx", {
                    "run_id": result_state["run_id"],
                    "title": "Engineering Approval Note",
                    "summary": "Generated by SOVARA.",
                    "observations": "\\n".join([str(t["result"]) for t in result_state.get("tool_results", [])]),
                    "evidence": str(result_state.get("retrieved_context", [])),
                    "calculations": "",
                    "findings": result_state.get("final_answer", ""),
                    "risk": result_state.get("risk_result", {}).get("risk_level", "UNKNOWN"),
                    "recommended_action": "Review required." if result_state.get("human_review_required") else "Proceed.",
                    "human_review_status": str(result_state.get("human_review_required", False))
                })
                result_state["tool_results"].append({"tool": "generate_docx", "result": res})
            except Exception as e:
                result_state["errors"].append(f"Doc gen error: {e}")
                
    except Exception as e:
        initial_state["errors"].append(str(e))
        initial_state["status"] = "FAILED"
        result_state = initial_state
        
    result_state["timing"]["total_ms"] = (time.time() - t0) * 1000
        
    return {
        "run_id": result_state["run_id"],
        "status": result_state["status"],
        "answer": result_state["final_answer"],
        "evidence": result_state["retrieved_context"],
        "citations": [c.get("chunk_id") for c in result_state["retrieved_context"]],
        "execution_trace": result_state["execution_events"],
        "deliverables": result_state["tool_results"],
        "verification": result_state["verification_result"],
        "risk": result_state["risk_result"],
        "human_review_required": result_state.get("human_review_required", False),
        "errors": result_state["errors"],
        "timing": result_state["timing"]
    }

if __name__ == "__main__":
    import sys
    import argparse
    
    parser = argparse.ArgumentParser(description="SOVARA AI Core Demo")
    parser.add_argument("query", nargs="*", default=["What is the recommended pressure for Pump P-999?"], help="The user query")
    parser.add_argument("--demo", action="store_true", help="Run the full hero demo with synthetic files")
    args = parser.parse_args()

    print("\\n==================================================")
    print(" SOVARA AI Core Demo")
    print("==================================================\\n")
    
    if args.demo:
        query = "Analyze the pump inspection information, examine the engineering drawing, retrieve relevant maintenance guidance from the internal knowledge base, analyze the inspection measurements, identify potential issues, perform required calculations, verify the evidence, assess risk, and prepare an engineering approval note."
        files = ["demo/inspection_report.pdf", "demo/pump_inspection.xlsx", "demo/pump_pid.png"]
    else:
        query = " ".join(args.query)
        files = []
        
    print(f"User Query: {query}")
    if files: print(f"Input Files: {files}")
    print("\\n")
    
    result = run_sovara_task(user_query=query, files=files)
    
    print(f"Status: {result['status']}")
    print(f"Risk: {result['risk']['risk_level'] if result['risk'] else 'N/A'}")
    print(f"Human Review: {result['human_review_required']}")
    print(f"Answer: {result['answer']}")
    print(f"Errors: {result['errors']}")
    print(f"Deliverables: {result['deliverables']}")
    
    print("\\nTiming metrics:")
    for k, v in result.get("timing", {}).items():
        print(f" - {k}: {v:.2f} ms")
        
    print("\\nExecution Trace:")
    for evt in result['execution_trace']:
        print(f" - {evt}")
    print(" - TASK_COMPLETED")