import sys

with open('main.py', 'r', encoding='utf-8') as f:
    code = f.read()

import re

old_block = re.search(r'res = registry\.execute\("generate_docx", \{.*?"human_review_status": str\(result_state\.get\("human_review_required", False\)\)\n\s*\}\)', code, re.DOTALL)

if old_block:
    new_block = '''sections = [
                    {"heading": "Summary", "content": "Generated by SOVARA."},
                    {"heading": "Observations [OBSERVED]", "content": "\\n".join([str(t["result"]) for t in result_state.get("tool_results", [])])},
                    {"heading": "Evidence [INFERRED]", "content": str(result_state.get("retrieved_context", []))},
                    {"heading": "Findings & Risk", "content": [result_state.get("final_answer", ""), f"Risk Level: {result_state.get('risk_result', {}).get('risk_level', 'UNKNOWN')}", f"Human Review Status: {result_state.get('human_review_required', False)}"]},
                    {"heading": "Recommended Action [RECOMMENDED]", "content": "Review required." if result_state.get("human_review_required") else "Proceed."}
                ]
                res = registry.execute("generate_docx", {
                    "filename": f"outputs/{result_state['run_id']}/Approval_Note.docx",
                    "title": "Engineering Approval Note",
                    "sections": sections
                })'''
    
    code = code[:old_block.start()] + new_block + code[old_block.end():]
    
    with open('main.py', 'w', encoding='utf-8') as f:
        f.write(code)
    print("Patched main.py successfully.")
else:
    print("Could not find block to replace.")
