"""
PDF Report Generator module.
Generates printable report documents (.pdf / .html).
"""

import time
from pathlib import Path
from typing import Dict, Any, Optional

from tools.c_tools.schemas import ExecutionResult, ExecutionError, ErrorCode
from tools.c_tools.file_ops.path_security import validate_workspace_path


def generate_pdf_report(
    filename: str,
    title: str,
    content: str,
    workspace_root: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generates a printable report document (.pdf / .html) with title and body styling.

    Args:
        filename: Target output filename (e.g., 'executive_summary.pdf').
        title: Main report title.
        content: Report content text or HTML body.
        workspace_root: Optional workspace root directory override.

    Returns:
        Structured ExecutionResult dictionary.
    """
    start_time = time.perf_counter()

    if not filename.endswith(".pdf") and not filename.endswith(".html"):
        filename += ".pdf"

    try:
        validated_path = validate_workspace_path(filename, workspace_root)
    except ValueError as e:
        return ExecutionResult(
            success=False,
            execution_time=time.perf_counter() - start_time,
            error=ExecutionError(code=ErrorCode.PATH_TRAVERSAL_ATTEMPT, message=str(e)),
        ).to_dict()

    validated_path.parent.mkdir(parents=True, exist_ok=True)

    html_template = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px; color: #1f2937; line-height: 1.6; }}
        h1 {{ color: #1e3a8a; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; }}
        .meta {{ font-size: 0.85em; color: #6b7280; margin-bottom: 24px; }}
        .content {{ background: #ffffff; padding: 16px 0; }}
        .footer {{ margin-top: 40px; font-size: 0.75em; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 12px; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <div class="meta">SOVARA Confidential Industrial Report</div>
    <div class="content">
        {content.replace('\n', '<br>')}
    </div>
    <div class="footer">Generated by SOVARA Tools & Output Subsystem</div>
</body>
</html>
"""

    format_used = "html_report"
    output_path = validated_path

    # Check reportlab or weasyprint if generating native pdf
    if filename.endswith(".pdf"):
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.pdfgen import canvas

            c = canvas.Canvas(str(validated_path), pagesize=letter)
            c.setFont("Helvetica-Bold", 18)
            c.drawString(50, 750, title)
            c.setFont("Helvetica", 10)
            c.setFillColorRGB(0.4, 0.4, 0.4)
            c.drawString(50, 735, "SOVARA Confidential Industrial Report")

            c.setFont("Helvetica", 11)
            c.setFillColorRGB(0, 0, 0)
            y = 700
            for line in content.splitlines():
                if y < 50:
                    c.showPage()
                    c.setFont("Helvetica", 11)
                    y = 750
                c.drawString(50, y, line[:90])  # Basic word wrap
                y -= 16

            c.save()
            format_used = "native_pdf_reportlab"
        except ImportError:
            # Fallback to HTML report file with notice
            output_path = validated_path.with_suffix(".html")
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(html_template)
            format_used = "html_printable_fallback"

    else:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_template)

    exec_time = time.perf_counter() - start_time
    file_size = output_path.stat().st_size

    return ExecutionResult(
        success=True,
        result={
            "filename": output_path.name,
            "path": str(output_path),
            "size_bytes": file_size,
            "format_used": format_used,
        },
        execution_time=exec_time,
    ).to_dict()
